[package]
name = "rpi-cnc"
version = "0.1.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2.21"
lazy_static = "0.2.8"

[build-dependencies]
gcc = "0.3.45"
cmacros = "0.1.0"